/*
A rotation of a string can be generated by moving characters 
one after another from beginning to end. For example, the rotations of
acab are acab, caba, abac, and baca.
*/
int findLCP(hashNode &node, int i,int j,int x,int y) {
    int len = min(j - i + 1, y - x + 1);
    int l = 1, r = len, ans = 0;
    while(l <= r) {
        int mid = l + r >> 1;
        if(node.getHash(i, i + mid - 1) == node.getHash(x, x + mid - 1)) {
            ans = mid;
            l = mid + 1;
        }
        else {
            r = mid - 1;
        }
    }
    return ans;
}

char compare(hashNode &node, int i, int j, int x, int y) {
    int lcp = findLCP(node, i, j, x, y);
    int len1 = j - i  + 1, len2 = y - x + 1;
    if(len1 == len2 && lcp == len1) return 'e';
    else if(len1 == lcp) return 's';
    else if(len2 == lcp) return 'b';
    else return (node.str[i + lcp] < node.str[x + lcp]) ? 's' : 'b';
}

void solve() {
    string str;
    cin >> str;
    int n = str.size();
    str += str;
    hashNode node(str);
    int l = 0, r = n - 1;
    for(int i = 0; i < n; i++) {
        char x = compare(node, l, r, i, i + n - 1);
        if(x == 'b') {
            l = i, r = i + n - 1;
        }
    }
    cout << str.substr(l, n) << "\n";
}   